In [1]:
import numpy as np

In [2]:
#1.Representation of numpy array
l=np.array([[[[11,8,6,12,7,9,8],[28,32,24,25,28,27,32]],        
                 [[7,10,10,-13,8,14,9],[26,31,25,21,28,30,22]],
                 [[9,6,13,8,6,6,13],[24,30,24,27,25,20,25]],
                 [[13,13,13,6,15,7,9],[29,20,24,23,21,24,29]]],
 
                [[[11,8,11,9,13,11,9],[24,24,24,31,20,23,32]],
                 [[13,7,10,15,13,7,10],[29,29,24,25,28,32,28]],
                 [[8,13,8,8,15,12,11],[30,27,28,21,27,31,25]],
                 [[13,12,15,13,11,7,6],[29,26,30,26,22,32,27]]],

                [[[5,3,4,5,3,3,21],[19,18,18,18,22,2,5]],
                 [[5,6,6,4,7,7,21],[20,18,19,20,20,7,2]],
                 [[7,6,5,7,7,5,19],[20,20,22,18,20,4,3]],
                 [[8,7,6,2,6,4,18],[20,19,22,18,19,4,7]]],
                
                [[[7,10,-10,11,11,11,22],[21,20,19,18,20,71,12]],
                 [[10,7,8,7,10,7,19],[21,22,21,18,20,7,8]],
                 [[10,10,12,7,7,7,21],[20,22,22,21,21,12,12]],
                 [[7,7,8,10,11,12,18],[21,22,21,18,18,10,7]]]])


In [3]:

l

array([[[[ 11,   8,   6,  12,   7,   9,   8],
         [ 28,  32,  24,  25,  28,  27,  32]],

        [[  7,  10,  10, -13,   8,  14,   9],
         [ 26,  31,  25,  21,  28,  30,  22]],

        [[  9,   6,  13,   8,   6,   6,  13],
         [ 24,  30,  24,  27,  25,  20,  25]],

        [[ 13,  13,  13,   6,  15,   7,   9],
         [ 29,  20,  24,  23,  21,  24,  29]]],


       [[[ 11,   8,  11,   9,  13,  11,   9],
         [ 24,  24,  24,  31,  20,  23,  32]],

        [[ 13,   7,  10,  15,  13,   7,  10],
         [ 29,  29,  24,  25,  28,  32,  28]],

        [[  8,  13,   8,   8,  15,  12,  11],
         [ 30,  27,  28,  21,  27,  31,  25]],

        [[ 13,  12,  15,  13,  11,   7,   6],
         [ 29,  26,  30,  26,  22,  32,  27]]],


       [[[  5,   3,   4,   5,   3,   3,  21],
         [ 19,  18,  18,  18,  22,   2,   5]],

        [[  5,   6,   6,   4,   7,   7,  21],
         [ 20,  18,  19,  20,  20,   7,   2]],

        [[  7,   6,   5,   7,   7,   5,  19],
         [

In [4]:
#2.shape and dimention of created array
l.shape

(4, 4, 2, 7)

In [5]:
l[0,0]

array([[11,  8,  6, 12,  7,  9,  8],
       [28, 32, 24, 25, 28, 27, 32]])

In [6]:
for i in range(4):
    print(l[i,0])

[[11  8  6 12  7  9  8]
 [28 32 24 25 28 27 32]]
[[11  8 11  9 13 11  9]
 [24 24 24 31 20 23 32]]
[[ 5  3  4  5  3  3 21]
 [19 18 18 18 22  2  5]]
[[  7  10 -10  11  11  11  22]
 [ 21  20  19  18  20  71  12]]


In [7]:
#do slicing(:)
print(l[i,0])

[[  7  10 -10  11  11  11  22]
 [ 21  20  19  18  20  71  12]]


In [8]:
#1st row min temp rpst
#2nd row rpst max temp
l[0,0,:,:5]

array([[11,  8,  6, 12,  7],
       [28, 32, 24, 25, 28]])

In [9]:
#3.Print the daily temperatures for the first week of each month.
l[:,:,:,1]

array([[[ 8, 32],
        [10, 31],
        [ 6, 30],
        [13, 20]],

       [[ 8, 24],
        [ 7, 29],
        [13, 27],
        [12, 26]],

       [[ 3, 18],
        [ 6, 18],
        [ 6, 20],
        [ 7, 19]],

       [[10, 20],
        [ 7, 22],
        [10, 22],
        [ 7, 22]]])

In [10]:
#4.Print the temperatures for Tuesday of each month.
l[1::2,:,1,0:5]

array([[[24, 24, 24, 31, 20],
        [29, 29, 24, 25, 28],
        [30, 27, 28, 21, 27],
        [29, 26, 30, 26, 22]],

       [[21, 20, 19, 18, 20],
        [21, 22, 21, 18, 20],
        [20, 22, 22, 21, 21],
        [21, 22, 21, 18, 18]]])

In [11]:
#5.Print only the maximum temperature for all the weekdays of Dec and Feb.
#month,all weeks,max/min,days
np.amax(l[1::2,:,1,0:5],axis=2)

array([[31, 29, 30, 30],
       [21, 22, 22, 22]])

In [12]:
np.amin(l[1::2,:,1,0:5],axis=2)

array([[20, 24, 21, 22],
       [18, 18, 20, 18]])

In [13]:
#6.Print all the days along with the week number in November when theminimum temperature was less than 8 degrees.
#p=index(ind)
s=l[0,:,0,:]
p=np.where(s<8)
print(s[p])

[  6   7   7 -13   6   6   6   6   7]


In [14]:
s

array([[ 11,   8,   6,  12,   7,   9,   8],
       [  7,  10,  10, -13,   8,  14,   9],
       [  9,   6,  13,   8,   6,   6,  13],
       [ 13,  13,  13,   6,  15,   7,   9]])

In [15]:
p

(array([0, 0, 1, 1, 2, 2, 2, 3, 3], dtype=int64),
 array([2, 4, 0, 3, 1, 4, 5, 3, 5], dtype=int64))

In [16]:
#7.Print all the weeks in Dec and Jan where the maximum temperature has cro
b=l[1:3,:,1,:]
b[0,0,0]
x=np.where(b>20)
print("weeks where days have temp greater than 20 in dec and jan")
print()
print('DEC jan')
for i in range(len(x[0])):
    print(x[0][i],"  ", x[1][i])

weeks where days have temp greater than 20 in dec and jan

DEC jan
0    0
0    0
0    0
0    0
0    0
0    0
0    1
0    1
0    1
0    1
0    1
0    1
0    1
0    2
0    2
0    2
0    2
0    2
0    2
0    2
0    3
0    3
0    3
0    3
0    3
0    3
0    3
1    0
1    2
1    3


In [17]:
#8.Check if there are any absurd values present in the dataset(like some temp which should not be present in the data)
# for all entire data
np.mean(l)

15.504464285714286

In [18]:
#along all axes
np.mean(l,axis=3)

array([[[ 8.71428571, 28.        ],
        [ 6.42857143, 26.14285714],
        [ 8.71428571, 25.        ],
        [10.85714286, 24.28571429]],

       [[10.28571429, 25.42857143],
        [10.71428571, 27.85714286],
        [10.71428571, 27.        ],
        [11.        , 27.42857143]],

       [[ 6.28571429, 14.57142857],
        [ 8.        , 15.14285714],
        [ 8.        , 15.28571429],
        [ 7.28571429, 15.57142857]],

       [[ 8.85714286, 25.85714286],
        [ 9.71428571, 16.71428571],
        [10.57142857, 18.57142857],
        [10.42857143, 16.71428571]]])

In [19]:
np.mean(l[0])

17.267857142857142

In [20]:
#9.What strategy would you use to handle such data points?
#(array, 25th or 75th) inter quartile range method
iqr=np.percentile(l,75)-np.percentile(l,25)

In [21]:
iqr

14.25

In [22]:
d=np.mean(l[0])-1.5*iqr
e=np.mean(l[0])+1.5*iqr

In [23]:
d

-4.107142857142858

In [24]:
np.where(l[0]<d)

(array([1], dtype=int64), array([0], dtype=int64), array([3], dtype=int64))

In [25]:

e

38.64285714285714

In [26]:
#10.Find and print the indexes of all the outlier(unusual) values present in the above dataset
np.where(l[0]>e)

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

In [27]:
iqr=np.percentile(l,75)-np.percentile(l,25)
f=np.mean(l[1])-1.5*iqr
g=np.mean(l[1])+1.5*iqr

In [28]:
f

-2.571428571428573

In [29]:
g

40.17857142857143

In [30]:
k=np.mean(l[2])-1.5*iqr
c=np.mean([2])+1.5*iqr

In [31]:

k

-10.107142857142858

In [32]:
c

23.375

In [33]:
a=np.mean(l[3])-1.5*iqr
b=np.mean(l[3])+1.5*iqr

In [34]:
a

-6.696428571428571

In [35]:
b

36.05357142857143

In [36]:
#11.Find the average max temperature for the winter months in Jaipur.
#nov=nov,all week,min temp, all days
l[0][l[0]<1]=np.mean(l[0,:,0,:])
l[0][l[0]>0]=np.mean(l[0,:,1,:])

In [37]:
l[1]

array([[[11,  8, 11,  9, 13, 11,  9],
        [24, 24, 24, 31, 20, 23, 32]],

       [[13,  7, 10, 15, 13,  7, 10],
        [29, 29, 24, 25, 28, 32, 28]],

       [[ 8, 13,  8,  8, 15, 12, 11],
        [30, 27, 28, 21, 27, 31, 25]],

       [[13, 12, 15, 13, 11,  7,  6],
        [29, 26, 30, 26, 22, 32, 27]]])

In [38]:
s=np.average(l)
np.max(s)

17.4375

In [39]:
#12.Find the weekly min avg temp for the month of Dec in Jaipur
t=np.average(l)
np.min(t)

17.4375

In [40]:
#13.Find the weekly min avg temp for the month of Dec in Jaipur
l[l==24]=5

In [41]:
l

array([[[[ 25,  25,  25,  25,  25,  25,  25],
         [ 25,  25,  25,  25,  25,  25,  25]],

        [[ 25,  25,  25,  25,  25,  25,  25],
         [ 25,  25,  25,  25,  25,  25,  25]],

        [[ 25,  25,  25,  25,  25,  25,  25],
         [ 25,  25,  25,  25,  25,  25,  25]],

        [[ 25,  25,  25,  25,  25,  25,  25],
         [ 25,  25,  25,  25,  25,  25,  25]]],


       [[[ 11,   8,  11,   9,  13,  11,   9],
         [  5,   5,   5,  31,  20,  23,  32]],

        [[ 13,   7,  10,  15,  13,   7,  10],
         [ 29,  29,   5,  25,  28,  32,  28]],

        [[  8,  13,   8,   8,  15,  12,  11],
         [ 30,  27,  28,  21,  27,  31,  25]],

        [[ 13,  12,  15,  13,  11,   7,   6],
         [ 29,  26,  30,  26,  22,  32,  27]]],


       [[[  5,   3,   4,   5,   3,   3,  21],
         [ 19,  18,  18,  18,  22,   2,   5]],

        [[  5,   6,   6,   4,   7,   7,  21],
         [ 20,  18,  19,  20,  20,   7,   2]],

        [[  7,   6,   5,   7,   7,   5,  19],
         [

In [42]:
u=np.average(l,1)

In [43]:
u

array([[[25.  , 25.  , 25.  , 25.  , 25.  , 25.  , 25.  ],
        [25.  , 25.  , 25.  , 25.  , 25.  , 25.  , 25.  ]],

       [[11.25, 10.  , 11.  , 11.25, 13.  ,  9.25,  9.  ],
        [23.25, 21.75, 17.  , 25.75, 24.25, 29.5 , 28.  ]],

       [[ 6.25,  5.5 ,  5.25,  4.5 ,  5.75,  4.75, 19.75],
        [19.75, 18.75, 20.25, 18.5 , 20.25,  4.25,  4.25]],

       [[ 8.5 ,  8.5 ,  4.5 ,  8.75,  9.75,  9.25, 20.  ],
        [20.75, 21.5 , 20.75, 18.75, 19.75, 25.  ,  9.75]]])

In [44]:
#14.Find the overall avg temp for the months Dec and Jan
v=np.average(l,2)

In [45]:
v

array([[[25. , 25. , 25. , 25. , 25. , 25. , 25. ],
        [25. , 25. , 25. , 25. , 25. , 25. , 25. ],
        [25. , 25. , 25. , 25. , 25. , 25. , 25. ],
        [25. , 25. , 25. , 25. , 25. , 25. , 25. ]],

       [[ 8. ,  6.5,  8. , 20. , 16.5, 17. , 20.5],
        [21. , 18. ,  7.5, 20. , 20.5, 19.5, 19. ],
        [19. , 20. , 18. , 14.5, 21. , 21.5, 18. ],
        [21. , 19. , 22.5, 19.5, 16.5, 19.5, 16.5]],

       [[12. , 10.5, 11. , 11.5, 12.5,  2.5, 13. ],
        [12.5, 12. , 12.5, 12. , 13.5,  7. , 11.5],
        [13.5, 13. , 13.5, 12.5, 13.5,  4.5, 11. ],
        [14. , 13. , 14. , 10. , 12.5,  4. , 12.5]],

       [[14. , 15. ,  4.5, 14.5, 15.5, 41. , 17. ],
        [15.5, 14.5, 14.5, 12.5, 15. ,  7. , 13.5],
        [15. , 16. , 17. , 14. , 14. ,  9.5, 16.5],
        [14. , 14.5, 14.5, 14. , 14.5, 11. , 12.5]]])

In [46]:
#15.Find the least temp experienced by the city in the month of Dec and Jan. Also print the exact date( Day/Week/Month) for the same.
k=np.min(l[1:3,:,:,:])
m1={0:"nov",1:"dec",2:"jan",3:"feb"}
w1={0:"week(1)",1:"week(2)",2:"week(3)",3:"week(4)"}
d1={0:"monday",1:"tuesday",2:"wednesday",3:"thrusday",4:"friday",5:"saturday",6:"sunday"}


In [47]:
k

2

In [48]:
m1

{0: 'nov', 1: 'dec', 2: 'jan', 3: 'feb'}

In [49]:

w1

{0: 'week(1)', 1: 'week(2)', 2: 'week(3)', 3: 'week(4)'}

In [50]:
d1

{0: 'monday',
 1: 'tuesday',
 2: 'wednesday',
 3: 'thrusday',
 4: 'friday',
 5: 'saturday',
 6: 'sunday'}

In [51]:
#16.Find the max temp in the month of Feb and return its date(Day/Week/Month)
z=np.where(l[1:3,:,:,:]==k)
z

(array([1, 1, 1], dtype=int64),
 array([0, 1, 3], dtype=int64),
 array([1, 1, 0], dtype=int64),
 array([5, 6, 3], dtype=int64))

In [52]:
for i in range(len(z[0])):
    print(m1[z[0][i]]," ",w1[z[1][i]]," ",d1[z[2][i]])

dec   week(1)   tuesday
dec   week(2)   tuesday
dec   week(4)   monday


In [53]:
l[3:,1,:]
np.max(l)

71

In [54]:
# 17Q Find the days in the month of Nov where the max temp of the day
#dropped below the avg temp of the month. As
a=l[0,:,1,:] 
a
y=np.average(l[0])
np.where(y>a)  # all nov maximume value  are not  less then to  average value

(array([], dtype=int64), array([], dtype=int64))

In [55]:
y

25.0

In [56]:
#q18.Convert the above dataset into an array where the weeks of the same month must be present in the same row, but belonging to different months should come in a row either below or above the selected month.

np.transpose(l)

array([[[[ 25,  11,   5,   7],
         [ 25,  13,   5,  10],
         [ 25,   8,   7,  10],
         [ 25,  13,   8,   7]],

        [[ 25,   5,  19,  21],
         [ 25,  29,  20,  21],
         [ 25,  30,  20,  20],
         [ 25,  29,  20,  21]]],


       [[[ 25,   8,   3,  10],
         [ 25,   7,   6,   7],
         [ 25,  13,   6,  10],
         [ 25,  12,   7,   7]],

        [[ 25,   5,  18,  20],
         [ 25,  29,  18,  22],
         [ 25,  27,  20,  22],
         [ 25,  26,  19,  22]]],


       [[[ 25,  11,   4, -10],
         [ 25,  10,   6,   8],
         [ 25,   8,   5,  12],
         [ 25,  15,   6,   8]],

        [[ 25,   5,  18,  19],
         [ 25,   5,  19,  21],
         [ 25,  28,  22,  22],
         [ 25,  30,  22,  21]]],


       [[[ 25,   9,   5,  11],
         [ 25,  15,   4,   7],
         [ 25,   8,   7,   7],
         [ 25,  13,   2,  10]],

        [[ 25,  31,  18,  18],
         [ 25,  25,  20,  18],
         [ 25,  21,  18,  21],
         [ 25,  26,

In [57]:
#q19.The above data is appropriate for an audience who follow the metric system of measurement. Create an array that holds the same data but presented in Fahrenheit.
cel=l
fahrenheit=(cel*1.8)+32
print("temp in fahrenheit:",fahrenheit)

temp in fahrenheit: [[[[ 77.   77.   77.   77.   77.   77.   77. ]
   [ 77.   77.   77.   77.   77.   77.   77. ]]

  [[ 77.   77.   77.   77.   77.   77.   77. ]
   [ 77.   77.   77.   77.   77.   77.   77. ]]

  [[ 77.   77.   77.   77.   77.   77.   77. ]
   [ 77.   77.   77.   77.   77.   77.   77. ]]

  [[ 77.   77.   77.   77.   77.   77.   77. ]
   [ 77.   77.   77.   77.   77.   77.   77. ]]]


 [[[ 51.8  46.4  51.8  48.2  55.4  51.8  48.2]
   [ 41.   41.   41.   87.8  68.   73.4  89.6]]

  [[ 55.4  44.6  50.   59.   55.4  44.6  50. ]
   [ 84.2  84.2  41.   77.   82.4  89.6  82.4]]

  [[ 46.4  55.4  46.4  46.4  59.   53.6  51.8]
   [ 86.   80.6  82.4  69.8  80.6  87.8  77. ]]

  [[ 55.4  53.6  59.   55.4  51.8  44.6  42.8]
   [ 84.2  78.8  86.   78.8  71.6  89.6  80.6]]]


 [[[ 41.   37.4  39.2  41.   37.4  37.4  69.8]
   [ 66.2  64.4  64.4  64.4  71.6  35.6  41. ]]

  [[ 41.   42.8  42.8  39.2  44.6  44.6  69.8]
   [ 68.   64.4  66.2  68.   68.   44.6  35.6]]

  [[ 44.6  42.8 

In [58]:
#q20.Sort the above data in descending order on the basis of weekly average for the month of Dec.
a=np.average(l[1,0])
b=np.average(l[1,1]) 
c=np.average(l[1,2])
d=np.average(l[1,3]) 
print(a)
print(b)
print(c)
print(d)

13.785714285714286
17.928571428571427
18.857142857142858
19.214285714285715


In [59]:
h=np.array([a,b,c,d])
print(h)

[13.78571429 17.92857143 18.85714286 19.21428571]


In [60]:
np.sort(h)[::-1]

array([19.21428571, 18.85714286, 17.92857143, 13.78571429])

In [61]:
#q21.Sort the temp of the first three days of each month in descending order on the basis of overall average for the whole winter.
a=np.average(l[0,:,:,0:3])
print(a)
b=np.average(l[1,:,:,0:3])
print(b)
c=np.average(l[2,:,:,0:3])
print(c)
d=np.average(l[3,:,:,0:3])
print(d)

25.0
15.708333333333334
12.625
14.083333333333334


In [62]:
e=np.average(l[:,:,:,0:3])
print(e)

16.854166666666668


In [63]:
f=np.array([a,b,c,d])
print(f)

[25.         15.70833333 12.625      14.08333333]


In [64]:
np.sort(f)[::-1]

array([25.        , 15.70833333, 14.08333333, 12.625     ])

In [65]:
#q22.Create an array that stores the difference between the min and max temp for each day in all the winter months.
a=l[:,:,0,:]
b=l[:,:,1,:]
dif=b-a
print(dif)

[[[  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0]]

 [[ -6  -3  -6  22   7  12  23]
  [ 16  22  -5  10  15  25  18]
  [ 22  14  20  13  12  19  14]
  [ 16  14  15  13  11  25  21]]

 [[ 14  15  14  13  19  -1 -16]
  [ 15  12  13  16  13   0 -19]
  [ 13  14  17  11  13  -1 -16]
  [ 12  12  16  16  13   0 -11]]

 [[ 14  10  29   7   9  60 -10]
  [ 11  15  13  11  10   0 -11]
  [ 10  12  10  14  14   5  -9]
  [ 14  15  13   8   7  -2 -11]]]


In [66]:
#q23.Find and store the difference between the max temp of two consecutive days for each month of winter season.
s=l[:,:,1,:]
arr=np.diff(s,axis=2)
print(arr)

[[[  0   0   0   0   0   0]
  [  0   0   0   0   0   0]
  [  0   0   0   0   0   0]
  [  0   0   0   0   0   0]]

 [[  0   0  26 -11   3   9]
  [  0 -24  20   3   4  -4]
  [ -3   1  -7   6   4  -6]
  [ -3   4  -4  -4  10  -5]]

 [[ -1   0   0   4 -20   3]
  [ -2   1   1   0 -13  -5]
  [  0   2  -4   2 -16  -1]
  [ -1   3  -4   1 -15   3]]

 [[ -1  -1  -1   2  51 -59]
  [  1  -1  -3   2 -13   1]
  [  2   0  -1   0  -9   0]
  [  1  -1  -3   0  -8  -3]]]


In [67]:
#q24.Find and store the difference between the minimum temp of two consecutive days for each month of the winter season.
u=l[:,:,0,:]
arr=np.diff(u,axis=2)
print(arr)

[[[  0   0   0   0   0   0]
  [  0   0   0   0   0   0]
  [  0   0   0   0   0   0]
  [  0   0   0   0   0   0]]

 [[ -3   3  -2   4  -2  -2]
  [ -6   3   5  -2  -6   3]
  [  5  -5   0   7  -3  -1]
  [ -1   3  -2  -2  -4  -1]]

 [[ -2   1   1  -2   0  18]
  [  1   0  -2   3   0  14]
  [ -1  -1   2   0  -2  14]
  [ -1  -1  -4   4  -2  14]]

 [[  3 -20  21   0   0  11]
  [ -3   1  -1   3  -3  12]
  [  0   2  -5   0   0  14]
  [  0   1   2   1   1   6]]]


In [68]:
#q25.Create an array by combining the data present in arrays created in q.23 and q.24, to store the difference between the min and max temp of each day of all the months for the whole winter season, in a single array
add_array=np.concatenate([s,u])
add_array.flatten()

array([ 25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,
        25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,
        25,  25,   5,   5,   5,  31,  20,  23,  32,  29,  29,   5,  25,
        28,  32,  28,  30,  27,  28,  21,  27,  31,  25,  29,  26,  30,
        26,  22,  32,  27,  19,  18,  18,  18,  22,   2,   5,  20,  18,
        19,  20,  20,   7,   2,  20,  20,  22,  18,  20,   4,   3,  20,
        19,  22,  18,  19,   4,   7,  21,  20,  19,  18,  20,  71,  12,
        21,  22,  21,  18,  20,   7,   8,  20,  22,  22,  21,  21,  12,
        12,  21,  22,  21,  18,  18,  10,   7,  25,  25,  25,  25,  25,
        25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  25,
        25,  25,  25,  25,  25,  25,  25,  25,  25,  25,  11,   8,  11,
         9,  13,  11,   9,  13,   7,  10,  15,  13,   7,  10,   8,  13,
         8,   8,  15,  12,  11,  13,  12,  15,  13,  11,   7,   6,   5,
         3,   4,   5,   3,   3,  21,   5,   6,   6,   4,   7,   